### ISSUE TITLE
Link to /trunk in https://omegat.org/download

### ISSUE THREAD

**Issue by kosivantsov** [omegat-org/omegat-website#16]
Since SF.net's SVN is happily frozen at pre-4.3 version, this "alpha" version should be named something different, not `/trunk`, and the link to it should be `https://sourceforge.net/p/omegat/code/ci/master/tarball`

**Comment by amake** [comment]
It should be called "master".

**Comment by briacp** [comment]
The reference to trunk was already removed (https://github.com/omegat-org/omegat-website/commit/a7bea5829aa1c505c8f52de1831a95a222fcec54). I updated the link to the master tree instead of the tarball as it would be stale after (https://github.com/omegat-org/omegat-website/commit/85ac1f9bd3eb8bfae7d9dc135a23b16bbb9d3147)
